"""Tests for colonymind.codegen.compiler."""

from __future__ import annotations

import ast
import pathlib
import re
import subprocess
import sys
from typing import Any

import pytest

import colonymind as cm
from colonymind.codegen.compiler import compile_to_code
from colonymind.codegen.errors import CardinalityError, CodegenError, UnboundInputError
from colonymind.codegen.naming import build_name_map
from colonymind.ir import Direction, Edge, Graph, Node, Paradigm, Port, PortRef, load_graph
from colonymind.nodes.examples import (
    Anova,
    GenerateHtmlSummary,
    ImputeMissing,
    LoadCsv,
    TrainClassifier,
)

REPO_ROOT = pathlib.Path(__file__).parent.parent


def _out_port(node: Node, name: str) -> Port:
    return next(p for p in node.ports if p.direction == Direction.OUT and p.name == name)


def _in_port(node: Node, name: str) -> Port:
    return next(p for p in node.ports if p.direction == Direction.IN and p.name == name)


def _graph(nodes: list[Node], edges: list[Edge] | None = None) -> Graph:
    edges = edges or []
    return Graph(nodes={n.id: n for n in nodes}, edges={e.id: e for e in edges})


def _vertical_slice_graph() -> Graph:
    """Helper to build the vertical slice graph programmatically."""
    load_csv_node = LoadCsv().instantiate(path="x.csv")
    impute_missing_node = ImputeMissing().instantiate()
    anova_node = Anova().instantiate(group_col="g", value_col="v")
    train_classifier_node = TrainClassifier().instantiate(target="y")
    generate_html_summary_node = GenerateHtmlSummary().instantiate()

    edge1 = Edge(
        source=PortRef(node_id=load_csv_node.id, port_id=_out_port(load_csv_node, "frame").id),
        target=PortRef(
            node_id=impute_missing_node.id, port_id=_in_port(impute_missing_node, "frame").id
        ),
    )
    edge2 = Edge(
        source=PortRef(
            node_id=impute_missing_node.id, port_id=_out_port(impute_missing_node, "frame").id
        ),
        target=PortRef(node_id=anova_node.id, port_id=_in_port(anova_node, "frame").id),
    )
    edge3 = Edge(
        source=PortRef(
            node_id=impute_missing_node.id, port_id=_out_port(impute_missing_node, "frame").id
        ),
        target=PortRef(
            node_id=train_classifier_node.id, port_id=_in_port(train_classifier_node, "frame").id
        ),
    )
    edge4 = Edge(
        source=PortRef(
            node_id=impute_missing_node.id, port_id=_out_port(impute_missing_node, "frame").id
        ),
        target=PortRef(
            node_id=generate_html_summary_node.id,
            port_id=_in_port(generate_html_summary_node, "frame").id,
        ),
    )

    return _graph(
        [
            load_csv_node,
            impute_missing_node,
            anova_node,
            train_classifier_node,
            generate_html_summary_node,
        ],
        [edge1, edge2, edge3, edge4],
    )


def test_empty_graph_compiles_to_stub() -> None:
    """Empty graph compiles to a valid, importable stub."""
    source = compile_to_code(Graph())
    assert '"""Generated by Colony Mind. Do not edit by hand."""' in source
    assert "def main() -> None:" in source
    assert 'if __name__ == "__main__":' in source
    assert "main()" in source
    assert "    pass" in source  # Ensure pass is inside main
    ast.parse(source)  # Should not raise SyntaxError


def test_single_source_node() -> None:
    """A graph with just one LoadCsv node compiles to source with one call and one import."""
    load_csv_node = LoadCsv().instantiate(path="x.csv")
    graph = _graph([load_csv_node])
    source = compile_to_code(graph)
    assert source.count("cm.data.load_csv(") == 1
    assert source.count("import colonymind as cm") == 1


def test_linear_chain_wires_upstream_variable() -> None:
    """LoadCsv -> ImputeMissing wires the upstream variable correctly."""
    load_csv_node = LoadCsv().instantiate(path="x.csv")
    impute_missing_node = ImputeMissing().instantiate()
    edge = Edge(
        source=PortRef(node_id=load_csv_node.id, port_id=_out_port(load_csv_node, "frame").id),
        target=PortRef(
            node_id=impute_missing_node.id, port_id=_in_port(impute_missing_node, "frame").id
        ),
    )
    graph = _graph([load_csv_node, impute_missing_node], [edge])

    source = compile_to_code(graph)
    name_map = build_name_map(graph)

    load_csv_var_name = name_map.var_for(load_csv_node.id, _out_port(load_csv_node, "frame").id)

    pattern = re.escape("cm.clean.impute_missing(") + r"\s*" + re.escape(load_csv_var_name)
    assert re.search(pattern, source)
    assert source.index("cm.data.load_csv(") < source.index("cm.clean.impute_missing(")


def test_fan_out_one_upstream_var_three_consumers() -> None:
    """Fan-out: one upstream var, three independent consumers."""
    graph = _vertical_slice_graph()
    source = compile_to_code(graph)
    name_map = build_name_map(graph)

    # ImputeMissing's output 'frame' should be the shared upstream variable
    impute_missing_node = next(n for n in graph.nodes.values() if n.type == "clean.impute_missing")
    impute_out_var_name = name_map.var_for(
        impute_missing_node.id, _out_port(impute_missing_node, "frame").id
    )

    # ruff format may wrap a call's first argument onto its own indented line,
    # so allow whitespace (not just a bare "(") between the call and the var.
    for call in ("cm.stats.anova(", "cm.ml.train_classifier(", "cm.reports.generate_html_summary("):
        pattern = re.escape(call) + r"\s*" + re.escape(impute_out_var_name)
        assert re.search(pattern, source), f"expected {call!r} to take {impute_out_var_name!r}"
    assert source.count("import colonymind as cm") == 1


def test_dangling_required_in_port_is_error() -> None:
    """Dangling required IN port is a hard error."""
    impute_missing_node = ImputeMissing().instantiate()
    graph = _graph([impute_missing_node])

    with pytest.raises(UnboundInputError) as exc_info:
        compile_to_code(graph)

    assert "Impute Missing" in str(exc_info.value)
    assert "frame" in str(exc_info.value)


def test_fan_in_cardinality_one_port_is_error() -> None:
    """Fan-in onto a Cardinality.ONE port is a hard error."""
    load_csv_node_a = LoadCsv().instantiate(path="a.csv")
    load_csv_node_b = LoadCsv().instantiate(path="b.csv")
    impute_missing_node = ImputeMissing().instantiate()

    impute_in_port_ref = PortRef(
        node_id=impute_missing_node.id, port_id=_in_port(impute_missing_node, "frame").id
    )

    edge_a = Edge(
        source=PortRef(node_id=load_csv_node_a.id, port_id=_out_port(load_csv_node_a, "frame").id),
        target=impute_in_port_ref,
    )
    edge_b = Edge(
        source=PortRef(node_id=load_csv_node_b.id, port_id=_out_port(load_csv_node_b, "frame").id),
        target=impute_in_port_ref,
    )

    graph = _graph([load_csv_node_a, load_csv_node_b, impute_missing_node], [edge_a, edge_b])

    # Graph construction succeeds (cardinality isn't checked until wiring is
    # resolved); compile_to_code is what raises CardinalityError.
    with pytest.raises(CardinalityError):
        compile_to_code(graph)


def test_non_functional_graph_rejected() -> None:
    """Non-functional graph is rejected with a clear error."""
    load_csv_node = LoadCsv().instantiate(path="x.csv")
    # Mutate the node's paradigm
    load_csv_node_declarative = load_csv_node.model_copy(update={"paradigm": Paradigm.DECLARATIVE})
    graph = _graph([load_csv_node_declarative])

    with pytest.raises(CodegenError) as exc_info:
        compile_to_code(graph)
    assert "Story 8" in str(exc_info.value)


def test_module_shape_main_guard_ruff_clean() -> None:
    """Module shape: def main() + guard, ruff-clean."""
    graph = _vertical_slice_graph()
    source = compile_to_code(graph)

    assert source.startswith('"""Generated by Colony Mind. Do not edit by hand."""')
    assert "def main() -> None:" in source
    assert 'if __name__ == "__main__":' in source
    assert "    main()" in source

    # Check with ruff
    # Mimic the invocation style from colonymind/codegen/formatting.py
    ruff_command = [sys.executable, "-m", "ruff", "check", "-"]
    process = subprocess.run(
        ruff_command, input=source, capture_output=True, text=True, check=False
    )
    assert process.returncode == 0, f"Ruff check failed:\n{process.stderr}"


def test_end_to_end_vertical_slice_runs(monkeypatch: pytest.MonkeyPatch) -> None:
    """End-to-end: vertical slice loads, compiles, and runs."""
    graph = load_graph(REPO_ROOT / "examples" / "vertical_slice" / "pipeline.json")
    source = compile_to_code(graph)

    # Assert call substrings and order
    load_csv_idx = source.index("cm.data.load_csv(")
    impute_missing_idx = source.index("cm.clean.impute_missing(")
    anova_idx = source.index("cm.stats.anova(")
    train_classifier_idx = source.index("cm.ml.train_classifier(")
    generate_html_summary_idx = source.index("cm.reports.generate_html_summary(")

    assert load_csv_idx < impute_missing_idx
    # Order of anova, train_classifier, generate_html_summary relative to impute_missing
    # is not strictly defined other than after it. Their internal order doesn't matter.
    assert impute_missing_idx < anova_idx
    assert impute_missing_idx < train_classifier_idx
    assert impute_missing_idx < generate_html_summary_idx

    assert source.count("cm.data.load_csv(") == 1
    assert source.count("cm.clean.impute_missing(") == 1
    assert source.count("cm.stats.anova(") == 1
    assert source.count("cm.ml.train_classifier(") == 1
    assert source.count("cm.reports.generate_html_summary(") == 1

    # Execute the compiled module
    original_cwd = pathlib.Path.cwd()
    monkeypatch.chdir(REPO_ROOT / "examples" / "vertical_slice")
    try:
        namespace: dict[str, Any] = {}
        # Use a fresh namespace for execution to avoid conflicts
        exec(compile(source, "<compiled_vertical_slice>", "exec"), namespace)
        namespace["main"]()
    except Exception as e:
        pytest.fail(f"Execution of compiled vertical slice failed: {e}")
    finally:
        monkeypatch.chdir(original_cwd)


def test_cm_compile_to_code_is_lazily_wired() -> None:
    """cm.compile_to_code is lazily wired."""
    script = """
import sys
import colonymind as cm

# colonymind.codegen should not be imported yet
assert 'colonymind.codegen' not in sys.modules

# Accessing cm.compile_to_code should trigger the import
_ = cm.compile_to_code

# Now it should be imported
assert 'colonymind.codegen' in sys.modules
"""
    result = subprocess.run(
        [sys.executable, "-c", script], capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, f"Subprocess failed:\n{result.stderr}\n{result.stdout}"
    assert "compile_to_code" in cm.__all__
