"""Tests for the declarative (nn.Module) codegen seam — Epic 2, Story 8."""

from __future__ import annotations

import ast
import pathlib
import subprocess
import sys

import pytest

from colonymind.codegen.compiler import compile_to_code
from colonymind.codegen.errors import CodegenError
from colonymind.codegen.executor import execute
from colonymind.ir import Direction, Graph, Node, Paradigm, Port, load_graph

REPO_ROOT = pathlib.Path(__file__).parent.parent
EXAMPLE = REPO_ROOT / "examples" / "declarative_module.json"

GOLDEN = '''"""Generated by Colony Mind. Do not edit by hand."""

import torch.nn as nn


class SimpleClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_12864 = nn.Linear(128, 64)
        self.relu = nn.ReLU()
        self.linear_6410 = nn.Linear(64, 10)

    def forward(self, x):
        x = self.linear_12864(x)
        x = self.relu(x)
        x = self.linear_6410(x)
        return x
'''


def test_compile_to_code_declarative_matches_golden():
    graph = load_graph(EXAMPLE)
    assert graph.paradigm is Paradigm.DECLARATIVE
    assert compile_to_code(graph) == GOLDEN


def test_compiled_declarative_parses_and_is_lint_clean():
    code = compile_to_code(load_graph(EXAMPLE))
    ast.parse(code)  # raises SyntaxError on failure
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "-"],
        input=code,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_execute_matches_compiled_structure():
    torch_nn = pytest.importorskip("torch.nn")
    graph = load_graph(EXAMPLE)

    # Compiled path: exec the generated module, instantiate the nn.Module subclass.
    code = compile_to_code(graph)
    namespace: dict = {}
    exec(compile(code, "<generated>", "exec"), namespace)
    module_cls = next(
        v for v in namespace.values() if isinstance(v, type) and issubclass(v, torch_nn.Module)
    )
    compiled_children = [repr(child) for child in module_cls().children()]

    # Reference path: execute(ir) returns the structural-twin architecture as an
    # inspectable list of layer reprs (a live torch module is not inspectable).
    results = execute(graph)
    executed_children = next(iter(results.values()))["layers"]

    assert compiled_children == executed_children
    assert len(compiled_children) == 3
    assert "Linear" in compiled_children[0]


def _agent_graph() -> Graph:
    node = Node(id="n-agent", type="agent.planner", paradigm=Paradigm.DECLARATIVE)
    return Graph(paradigm=Paradigm.DECLARATIVE, name="agent", nodes={node.id: node}, edges={})


def test_agent_target_deferred_to_epic_11_compile():
    with pytest.raises(CodegenError, match="Epic 11"):
        compile_to_code(_agent_graph())


def test_agent_target_deferred_to_epic_11_execute():
    with pytest.raises(CodegenError, match="Epic 11"):
        execute(_agent_graph())


def _unsupported_layer_graph() -> Graph:
    conv = Node(
        id="n-conv",
        type="nn.conv2d",
        paradigm=Paradigm.DECLARATIVE,
        ports=[
            Port(id="p-conv-in", name="x", direction=Direction.IN, data_type="Tensor"),
            Port(id="p-conv-out", name="out", direction=Direction.OUT, data_type="Tensor"),
        ],
    )
    subgraph = Graph(
        paradigm=Paradigm.DECLARATIVE,
        name="body",
        nodes={conv.id: conv},
        edges={},
    )
    module = Node(id="n-module", type="nn.module", paradigm=Paradigm.DECLARATIVE, subgraph=subgraph)
    return Graph(paradigm=Paradigm.DECLARATIVE, name="m", nodes={module.id: module}, edges={})


def test_unsupported_layer_deferred_to_epic_10():
    with pytest.raises(CodegenError, match="Epic 10"):
        compile_to_code(_unsupported_layer_graph())
