"""Tests for the build-time UI contract export (scripts/export_ui_contracts.py).

Mirrors the staleness-test pattern in tests/test_rules_artifact.py: the committed JSON under
ui/src/generated/ must always equal what emergentflow.server.service currently produces, so the
canvas build never drifts from the SDK contract (ADR 0014 Decision 5).
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys

from emergentflow.server.service import (
    get_catalog,
    get_mutation_schema,
    get_schema,
    get_session_event_schema,
)

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from export_ui_contracts import export_ui_contracts  # noqa: E402


def _fresh_contracts() -> dict[str, object]:
    """Return ``{"schema", "catalog", "mutation_schema", "session_event_schema"}`` produced by a
    CLEAN interpreter.

    The committed artifacts are generated by ``export_ui_contracts.py`` in a fresh process
    (only the built-in reference nodes are registered). The in-process pytest interpreter, by
    contrast, has dummy ``test.*`` node types registered at import time by other test modules
    (e.g. ``test_codegen_executor`` / ``test_codegen_equivalence`` use module-level ``@register``,
    which must hit the global registry so ``compile_to_code``/``execute`` can resolve them). So
    the staleness check must compare the committed files against a clean-process catalog, not the
    polluted in-process ``get_catalog()``.
    """
    code = (
        "import json,sys;"
        "from emergentflow.server.service import get_schema,get_catalog,"
        "get_mutation_schema,get_session_event_schema;"
        "json.dump({'schema':get_schema(),'catalog':get_catalog(),"
        "'mutation_schema':get_mutation_schema(),"
        "'session_event_schema':get_session_event_schema()},sys.stdout)"
    )
    out = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    return json.loads(out.stdout)


def test_export_ui_contracts_round_trips(tmp_path: pathlib.Path):
    export_ui_contracts(tmp_path)

    with open(tmp_path / "ir.schema.json", encoding="utf-8") as fh:
        schema_data = json.load(fh)
    assert schema_data == get_schema()

    with open(tmp_path / "catalog.json", encoding="utf-8") as fh:
        catalog_data = json.load(fh)
    assert catalog_data == get_catalog()

    with open(tmp_path / "mutation.schema.json", encoding="utf-8") as fh:
        mutation_schema_data = json.load(fh)
    assert mutation_schema_data == get_mutation_schema()

    with open(tmp_path / "session_event.schema.json", encoding="utf-8") as fh:
        session_event_schema_data = json.load(fh)
    assert session_event_schema_data == get_session_event_schema()


def test_committed_ir_schema_not_stale():
    committed = REPO_ROOT / "ui" / "src" / "generated" / "ir.schema.json"
    with open(committed, encoding="utf-8") as fh:
        data = json.load(fh)
    assert data == _fresh_contracts()["schema"], (
        "Committed ir.schema.json is stale. "
        "Run `uv run python scripts/export_ui_contracts.py` to regenerate."
    )


def test_committed_catalog_not_stale():
    committed = REPO_ROOT / "ui" / "src" / "generated" / "catalog.json"
    with open(committed, encoding="utf-8") as fh:
        data = json.load(fh)
    assert data == _fresh_contracts()["catalog"], (
        "Committed catalog.json is stale. "
        "Run `uv run python scripts/export_ui_contracts.py` to regenerate."
    )


def test_committed_mutation_schema_not_stale():
    committed = REPO_ROOT / "ui" / "src" / "generated" / "mutation.schema.json"
    with open(committed, encoding="utf-8") as fh:
        data = json.load(fh)
    assert data == _fresh_contracts()["mutation_schema"], (
        "Committed mutation.schema.json is stale. "
        "Run `uv run python scripts/export_ui_contracts.py` to regenerate."
    )


def test_committed_session_event_schema_not_stale():
    committed = REPO_ROOT / "ui" / "src" / "generated" / "session_event.schema.json"
    with open(committed, encoding="utf-8") as fh:
        data = json.load(fh)
    assert data == _fresh_contracts()["session_event_schema"], (
        "Committed session_event.schema.json is stale. "
        "Run `uv run python scripts/export_ui_contracts.py` to regenerate."
    )


def test_graph_mutation_fixture_round_trips() -> None:
    """The committed sample GraphMutation fixture (tests/fixtures/graph_mutation_sample.json)
    deserializes back to an identical GraphMutation -- the Python-side half of the
    cross-language contract; a UI-side ajv test can validate the SAME file against
    mutation.schema.json (out of scope here, see Story 4's validateMutation.test.ts)."""
    from emergentflow.ir.mutation import GraphMutation

    fixture_path = REPO_ROOT / "tests" / "fixtures" / "graph_mutation_sample.json"
    data = json.loads(fixture_path.read_text())
    mutation = GraphMutation.model_validate(data)
    assert mutation.model_dump(mode="json") == data
