"""Story 7's export + round-trip suite.

Proves the script `ef.export_script` writes to disk (a) runs as a standalone
subprocess and (b) when imported and `main()`-called yields artifacts equal to
`execute(ir)` — the headline gate that the exported `.py` runs outside the
canvas and produces the same artifacts as the in-process reference executor.
"""

from __future__ import annotations

import ast
import importlib.util
import keyword
import pathlib
import subprocess
import sys

import pytest

import emergentflow as ef
from emergentflow.codegen.compiler import _assemble
from emergentflow.codegen.executor import execute
from emergentflow.ir import Graph, load_graph
from tests.test_codegen_equivalence import _assert_equiv, _canon, _volatile_ports

REPO_ROOT = pathlib.Path(__file__).parent.parent
SLICE_DIR = REPO_ROOT / "examples" / "vertical_slice"


def _import_script(path: pathlib.Path):
    """Import the exported .py file at *path* as a fresh module object."""
    spec = importlib.util.spec_from_file_location("cm_exported_script", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _leaf_var_to_port(graph) -> dict[str, tuple[str, str]]:
    """For each leaf OUT-port var (returned by main()), its (node_id, port_name)."""
    assembled = _assemble(graph)
    leaf = set(assembled.leaf_vars)
    return {
        var: (node_id, port_name) for node_id, port_name, var in assembled.out_ports if var in leaf
    }


def test_export_writes_script_and_requirements(tmp_path: pathlib.Path) -> None:
    """export_script writes a named .py + pinned requirements.txt with a banner."""
    graph = load_graph(SLICE_DIR / "pipeline.json")
    result = ef.export_script(graph, tmp_path)

    assert result.script_path.exists()
    assert result.requirements_path.exists()

    assert result.script_path.name == "vertical_slice_example.py"
    assert result.requirements_path.read_text() == f"emergentflow=={ef.__version__}\n"

    script_text = result.script_path.read_text()
    assert script_text.startswith(f"# Generated by Emergent Flow v{ef.__version__}.")

    docstring = ast.get_docstring(ast.parse(script_text))
    assert docstring is not None
    assert docstring.startswith("Generated by Emergent Flow")


def test_exported_script_is_ruff_clean(tmp_path: pathlib.Path) -> None:
    """The exported script parses cleanly and passes ruff check."""
    graph = load_graph(SLICE_DIR / "pipeline.json")
    result = ef.export_script(graph, tmp_path)

    proc = subprocess.run(
        [sys.executable, "-m", "ruff", "check", str(result.script_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr

    ast.parse(result.script_path.read_text())


def test_exported_script_reads_like_demo(tmp_path: pathlib.Path) -> None:
    """The exported script contains the same SDK calls, in the same order, as demo.py."""
    graph = load_graph(SLICE_DIR / "pipeline.json")
    result = ef.export_script(graph, tmp_path)
    script_text = result.script_path.read_text()

    load_csv_idx = script_text.index("ef.data.load_csv(")
    impute_missing_idx = script_text.index("ef.clean.impute_missing(")
    anova_idx = script_text.index("ef.stats.anova(")
    train_classifier_idx = script_text.index("ef.ml.train_classifier(")
    generate_html_summary_idx = script_text.index("ef.reports.generate_html_summary(")

    assert load_csv_idx < impute_missing_idx
    assert impute_missing_idx < anova_idx
    assert impute_missing_idx < train_classifier_idx
    assert impute_missing_idx < generate_html_summary_idx


def test_exported_script_runs_as_subprocess(tmp_path: pathlib.Path) -> None:
    """The exported script runs standalone (real subprocess, no canvas)."""
    graph = load_graph(SLICE_DIR / "pipeline.json")
    result = ef.export_script(graph, tmp_path)

    proc = subprocess.run(
        [sys.executable, str(result.script_path)],
        cwd=str(SLICE_DIR),
        capture_output=True,
        text=True,
        check=False,
        timeout=180,
    )
    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert proc.stdout.strip()


def test_roundtrip_main_artifacts_equal_execute(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """execute(ir) artifacts equal the artifacts produced by the exported script's main()."""
    graph = load_graph(SLICE_DIR / "pipeline.json")
    result = ef.export_script(graph, tmp_path)
    leaf_map = _leaf_var_to_port(graph)
    volatile = _volatile_ports(graph)

    monkeypatch.chdir(SLICE_DIR)

    exec_results = execute(graph)
    module = _import_script(result.script_path)
    main_results = module.main()

    assert set(main_results) == set(leaf_map)

    for var, value in main_results.items():
        node_id, port_name = leaf_map[var]
        exec_value = exec_results[node_id][port_name]
        if (node_id, port_name) in volatile:
            ev = _canon(exec_value)
            cv = _canon(value)
            assert isinstance(ev, str) and isinstance(cv, str) and ev and cv
        else:
            _assert_equiv(_canon(exec_value), _canon(value), f"{node_id}.{port_name}")


@pytest.mark.parametrize(
    ("graph_name", "expected_stem"),
    [
        ("Vertical Slice Example", "vertical_slice_example"),
        ("2024 Report", "_2024_report"),  # leading digit -> not a legal module name
        ("class", "class_"),  # keyword -> would shadow / be a SyntaxError to import
        ("match", "match_"),  # soft keyword
        ("café", "caf"),  # non-ASCII transliterated away
        ("日本語", "pipeline"),  # all-non-ASCII -> fallback
        ("", "pipeline"),  # empty -> fallback
        (None, "pipeline"),  # unnamed graph -> fallback
    ],
)
def test_export_filename_stem_is_a_valid_identifier(
    tmp_path: pathlib.Path, graph_name: str | None, expected_stem: str
) -> None:
    """The exported .py stem is always a valid, importable Python identifier."""
    graph = Graph(name=graph_name)
    result = ef.export_script(graph, tmp_path)
    assert result.script_path.name == f"{expected_stem}.py"
    # The stem must be a legal module name so the script is importable by name,
    # not just runnable by path (parity with emergentflow.codegen.naming).
    assert expected_stem.isidentifier() and not keyword.iskeyword(expected_stem)
