"""Tests for colonymind.codegen.formatting."""

from __future__ import annotations

import subprocess
import sys

import pytest

from colonymind.codegen.errors import CodegenError
from colonymind.codegen.formatting import format_source


def _ruff_isort_clean(code: str) -> bool:
    """True if *code* has no I001 (import-order) violations under ruff."""
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--select", "I", "-"],
        input=code,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def test_format_source_normalizes_quotes() -> None:
    """The format pass normalizes single quotes to double quotes."""
    formatted = format_source("x = 'a'\n")
    assert formatted == 'x = "a"\n'


def test_format_source_organizes_mixed_imports() -> None:
    """A stdlib + third-party import mix is reordered isort-clean.

    `ruff format` alone never reorders imports, so without the import-organize
    pass the whole-graph compiler would emit I001-dirty output as soon as any
    node contributed a stdlib import alongside the SDK's `import colonymind`.
    """
    source = (
        '"""Generated by Colony Mind. Do not edit by hand."""\n'
        "\n"
        "import colonymind as cm\n"
        "import os\n"
        "\n"
        "\n"
        "def main() -> None:\n"
        "    x = os.getcwd()\n"
        "    y = cm.__version__\n"
        "    del x, y\n"
    )
    # The raw assembled source is isort-dirty (third-party before stdlib)...
    assert not _ruff_isort_clean(source)

    formatted = format_source(source)

    # ...but the formatted output is isort-clean, with stdlib grouped first.
    assert _ruff_isort_clean(formatted)
    assert formatted.index("import os") < formatted.index("import colonymind as cm")


def test_format_source_raises_on_unparseable() -> None:
    """Source that does not parse surfaces as a CodegenError, not a crash."""
    with pytest.raises(CodegenError):
        format_source("def main(:\n    pass\n")
