"""Tests for the build-time UI contract export (scripts/export_ui_contracts.py).

Mirrors the staleness-test pattern in tests/test_rules_artifact.py: the committed JSON under
ui/src/generated/ must always equal what colonymind.server.service currently produces, so the
canvas build never drifts from the SDK contract (ADR 0014 Decision 5).
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys

from colonymind.server.service import get_catalog, get_schema

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from export_ui_contracts import export_ui_contracts  # noqa: E402


def _fresh_contracts() -> dict[str, object]:
    """Return ``{"schema", "catalog"}`` produced by a CLEAN interpreter.

    The committed artifacts are generated by ``export_ui_contracts.py`` in a fresh process
    (only the built-in reference nodes are registered). The in-process pytest interpreter, by
    contrast, has dummy ``test.*`` node types registered at import time by other test modules
    (e.g. ``test_codegen_executor`` / ``test_codegen_equivalence`` use module-level ``@register``,
    which must hit the global registry so ``compile_to_code``/``execute`` can resolve them). So
    the staleness check must compare the committed files against a clean-process catalog, not the
    polluted in-process ``get_catalog()``.
    """
    code = (
        "import json,sys;"
        "from colonymind.server.service import get_schema,get_catalog;"
        "json.dump({'schema':get_schema(),'catalog':get_catalog()},sys.stdout)"
    )
    out = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    return json.loads(out.stdout)


def test_export_ui_contracts_round_trips(tmp_path: pathlib.Path):
    export_ui_contracts(tmp_path)

    with open(tmp_path / "ir.schema.json", encoding="utf-8") as fh:
        schema_data = json.load(fh)
    assert schema_data == get_schema()

    with open(tmp_path / "catalog.json", encoding="utf-8") as fh:
        catalog_data = json.load(fh)
    assert catalog_data == get_catalog()


def test_committed_ir_schema_not_stale():
    committed = REPO_ROOT / "ui" / "src" / "generated" / "ir.schema.json"
    with open(committed, encoding="utf-8") as fh:
        data = json.load(fh)
    assert data == _fresh_contracts()["schema"], (
        "Committed ir.schema.json is stale. "
        "Run `uv run python scripts/export_ui_contracts.py` to regenerate."
    )


def test_committed_catalog_not_stale():
    committed = REPO_ROOT / "ui" / "src" / "generated" / "catalog.json"
    with open(committed, encoding="utf-8") as fh:
        data = json.load(fh)
    assert data == _fresh_contracts()["catalog"], (
        "Committed catalog.json is stale. "
        "Run `uv run python scripts/export_ui_contracts.py` to regenerate."
    )
