"""
colonymind.codegen.export
~~~~~~~~~~~~~~~~~~~~~~~~~~
The I/O-isolated script exporter for the code-generation engine (Epic 2, Story 7).

`export_script` is the I/O wrapper around the pure `compile_to_code`
(`colonymind/codegen/compiler.py`): it calls `compile_to_code` to get the
compiled Python source, prepends a one-line version/reproduce banner comment,
and writes the result to a standalone `.py` script alongside a pinned
`requirements.txt` in a destination directory. `compile_to_code` itself stays
pure (no I/O) per ADR 0002; all filesystem access lives here.

This module produces a single runnable script, not a full project export.
The richer multi-file project-export format (e.g. packaging, configs, tests)
is Epic 14.
"""

from __future__ import annotations

import keyword
import pathlib
import re
from dataclasses import dataclass

from colonymind import __version__
from colonymind.api import public_op
from colonymind.codegen.compiler import compile_to_code
from colonymind.ir import Graph


@dataclass(frozen=True)
class ExportResult:
    """Filesystem paths written by :func:`export_script`."""

    script_path: pathlib.Path
    requirements_path: pathlib.Path


def _slug_filename(name: str | None) -> str:
    """Derive a safe snake_case .py stem from a graph name; fall back to 'pipeline'.

    The stem is a valid Python identifier so the exported file is importable by
    its bare module name (e.g. a graph named "2024 Report" -> ``_2024_report``,
    not ``2024_report`` which is not a legal module name), mirroring the
    identifier discipline in :mod:`colonymind.codegen.naming`.
    """
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", (name or "").strip().lower()).strip("_")
    if not slug:
        return "pipeline"
    if slug[0].isdigit():
        slug = f"_{slug}"
    if keyword.iskeyword(slug) or keyword.issoftkeyword(slug):
        slug = f"{slug}_"
    return slug


@public_op(name="cm.export_script")
def export_script(
    graph: Graph,
    dest: str | pathlib.Path,
    *,
    name: str | None = None,
) -> ExportResult:
    """Compile *graph* and write a standalone runnable script plus a pinned
    ``requirements.txt`` into the *dest* directory.

    Args:
        graph: The IR graph to export.
        dest: Destination directory (created, with parents, if missing).
        name: Optional base filename stem (no extension). Defaults to a slug of
            ``graph.name``, or ``"pipeline"`` if the graph is unnamed.

    Note:
        Export is idempotent and overwrites: ``<stem>.py`` and the fixed
        ``requirements.txt`` in *dest* are replaced if they already exist. Pass a
        distinct ``dest`` (or ``name``) per graph to avoid clobbering, since two
        different graphs can slug to the same stem.

    Returns:
        An :class:`ExportResult` with the written ``script_path`` and
        ``requirements_path``.
    """
    dest_dir = pathlib.Path(dest)
    dest_dir.mkdir(parents=True, exist_ok=True)

    source = compile_to_code(graph)

    banner = (
        f"# Generated by Colony Mind v{__version__}. Reproduce: pip install -r requirements.txt\n"
    )
    script_text = banner + source

    stem = _slug_filename(name if name is not None else graph.name)

    script_path = dest_dir / f"{stem}.py"
    script_path.write_text(script_text, encoding="utf-8")

    requirements_path = dest_dir / "requirements.txt"
    requirements_path.write_text(f"colonymind=={__version__}\n", encoding="utf-8")

    return ExportResult(script_path=script_path, requirements_path=requirements_path)
