"""
emergentflow.codegen.export
~~~~~~~~~~~~~~~~~~~~~~~~~~
The I/O-isolated script exporter for the code-generation engine (Epic 2, Story 7).

`export_script` is the I/O wrapper around the pure `compile_to_code`
(`emergentflow/codegen/compiler.py`): it calls `compile_to_code` to get the
compiled Python source, prepends a one-line version/reproduce banner comment,
and writes the result to a standalone `.py` script alongside a pinned
`requirements.txt` in a destination directory. `compile_to_code` itself stays
pure (no I/O) per ADR 0002; all filesystem access lives here.

This module produces a single runnable script, not a full project export.
The richer multi-file project-export format (e.g. packaging, configs, tests)
is Epic 14.
"""

from __future__ import annotations

import keyword
import pathlib
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

from emergentflow import __version__
from emergentflow.api import public_op
from emergentflow.codegen.compiler import compile_to_code
from emergentflow.ir import Graph
from emergentflow.research.reproducibility import capture_run

if TYPE_CHECKING:
    from emergentflow.research.report import Report


@dataclass(frozen=True)
class ExportResult:
    """Filesystem paths written by :func:`export_script`."""

    script_path: pathlib.Path
    requirements_path: pathlib.Path


@dataclass(frozen=True)
class ReportExportResult:
    """Filesystem paths written by :func:`export_report`."""

    html_path: pathlib.Path
    pdf_path: pathlib.Path | None


def _slug_filename(name: str | None, *, default: str = "pipeline") -> str:
    """Derive a safe snake_case filename stem from *name*; fall back to *default*.

    The stem is a valid Python identifier so an exported script is importable by
    its bare module name (e.g. a graph named "2024 Report" -> ``_2024_report``,
    not ``2024_report`` which is not a legal module name), mirroring the
    identifier discipline in :mod:`emergentflow.codegen.naming`.
    """
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", (name or "").strip().lower()).strip("_")
    if not slug:
        return default
    if slug[0].isdigit():
        slug = f"_{slug}"
    if keyword.iskeyword(slug) or keyword.issoftkeyword(slug):
        slug = f"{slug}_"
    return slug


@public_op(name="ef.export_script")
def export_script(
    graph: Graph,
    dest: str | pathlib.Path,
    *,
    name: str | None = None,
) -> ExportResult:
    """Compile *graph* and write a standalone runnable script plus a pinned
    ``requirements.txt`` into the *dest* directory.

    Args:
        graph: The IR graph to export.
        dest: Destination directory (created, with parents, if missing).
        name: Optional base filename stem (no extension). Defaults to a slug of
            ``graph.name``, or ``"pipeline"`` if the graph is unnamed.

    Note:
        Export is idempotent and overwrites: ``<stem>.py`` and the fixed
        ``requirements.txt`` in *dest* are replaced if they already exist. Pass a
        distinct ``dest`` (or ``name``) per graph to avoid clobbering, since two
        different graphs can slug to the same stem.

    Returns:
        An :class:`ExportResult` with the written ``script_path`` and
        ``requirements_path``.
    """
    dest_dir = pathlib.Path(dest)
    dest_dir.mkdir(parents=True, exist_ok=True)

    source = compile_to_code(graph)

    banner = (
        f"# Generated by Emergent Flow v{__version__}. Reproduce: pip install -r requirements.txt\n"
    )
    capture = capture_run(graph)
    if capture.seeds or capture.content_hashes or capture.params:
        repro_lines = ["# Reproducibility:"]
        if capture.seeds:
            repro_lines.append(f"#   seeds: {capture.seeds!r}")
        if capture.content_hashes:
            repro_lines.append(f"#   content_hashes: {capture.content_hashes!r}")
        if capture.params:
            repro_lines.append(f"#   params: {capture.params!r}")
        banner += "\n".join(repro_lines) + "\n"
    script_text = banner + source

    stem = _slug_filename(name if name is not None else graph.name)

    script_path = dest_dir / f"{stem}.py"
    script_path.write_text(script_text, encoding="utf-8")

    requirements_path = dest_dir / "requirements.txt"
    requirements_path.write_text(f"emergentflow=={__version__}\n", encoding="utf-8")

    return ExportResult(script_path=script_path, requirements_path=requirements_path)


@public_op(name="ef.export_report")
def export_report(
    report: Report,
    dest: str | pathlib.Path,
    *,
    name: str | None = None,
) -> ReportExportResult:
    """Write *report*'s rendered HTML (and PDF, if rendered) into the *dest* directory.

    Mirrors :func:`export_script`: the pure ``build_report``
    (``emergentflow/research/report.py``) computes the ``Report``; this function is the only
    place that touches the filesystem for it.

    Args:
        report: The composed report to write out.
        dest: Destination directory (created, with parents, if missing).
        name: Optional base filename stem (no extension). Defaults to a slug of
            ``report.meta.title``, or ``"report"`` if blank.

    Note:
        Export is idempotent and overwrites: ``<stem>.html`` (and ``<stem>.pdf`` when
        ``report.pdf_bytes`` is not ``None``) in *dest* are replaced if they already exist.

    Returns:
        A :class:`ReportExportResult` with the written ``html_path`` and, when a PDF was
        rendered, ``pdf_path`` (``None`` otherwise).
    """
    dest_dir = pathlib.Path(dest)
    dest_dir.mkdir(parents=True, exist_ok=True)

    stem = _slug_filename(name if name is not None else report.meta.title, default="report")

    html_path = dest_dir / f"{stem}.html"
    html_path.write_text(report.html, encoding="utf-8")

    pdf_path: pathlib.Path | None = None
    if report.pdf_bytes is not None:
        pdf_path = dest_dir / f"{stem}.pdf"
        pdf_path.write_bytes(report.pdf_bytes)

    return ReportExportResult(html_path=html_path, pdf_path=pdf_path)
